version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8011:5000"
  prom:
    build: ./prometheus
    ports:
      - "8061:9090"
    volumes:
      - prometheus_data:/prometheus
  grafana:
    build: ./grafana
    ports:
      - "9011:9011"
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  prometheus_data:
  grafana_data:
